### PR TITLE
dose rates,spectral wghts implementation

### LINKED ISSUE #102: Dose rates, spectral wghts implementation
Initially 11 or 28 spectral wghts are fully developed.  Code is similar to quantum_yield layout and style.

### LINKED ISSUE #104: remove src/environment.F90
Remove the file src/environment.F90. It is not needed for tuvx.

### PR DESCRIPTION
**Pull request by stacywalters**
closes #102

### CODE REVIEW

**Comment by stacywalters** [comment]
Kyle,

I'll cook up a case where this should fail.

Stacy

**Comment by stacywalters** [comment]
Kyle,

I assume you mean the "write(msg,*) ... " fails at runtime.  Is that
correct.  And if that is the case
then do you have a specific example?

Stacy

**Comment by K20shores** [comment]
@stacywalters Yes, the "write(msg,*) ... " fails at runtime. The specific example I saw this happen in was in the acetone cross section. I refactored that to put the message [directly into the assert](https://github.com/NCAR/photo-decomp/blob/32-add-unit-tests-for-radxfer_cross_sectiontypef90-functions/src/cross_sections/acetone-ch3co_ch3.F90#L138). I forced the failure to happen in `gdb` which is actually where I saw the failure happen. Does that give enough context or do you need more from me?

**Comment by stacywalters** [comment]
Kyle,

That is plenty of context.  All code fragments "writ(msg, ... " wherein msg
is defined as character(len=:), allocatable
will fail if executed.  I plan to clean this up in a followup PR.

Stacy

**Pull request merged**
